function generateLogic(){

const svg =
document.getElementById("ladderSVG");

svg.innerHTML = `
<line x1="50" y1="20" x2="50" y2="450" class="rail"/>
<line x1="950" y1="20" x2="950" y2="450" class="rail"/>
`;

drawRung(100);

}

function drawRung(y){

const svg =
document.getElementById("ladderSVG");

svg.innerHTML += `

<!-- Rung Line -->
<line x1="50" y1="${y}" x2="950" y2="${y}" class="rung"/>

<!-- XIC Contact -->
<line x1="150" y1="${y-20}" x2="150" y2="${y+20}" class="contact"/>
<line x1="180" y1="${y-20}" x2="180" y2="${y+20}" class="contact"/>

<text x="135" y="${y+40}" class="label">
Start_PB
</text>

<!-- XIO Contact -->
<line x1="300" y1="${y-20}" x2="300" y2="${y+20}" class="contact"/>
<line x1="330" y1="${y-20}" x2="330" y2="${y+20}" class="contact"/>
<line x1="295" y1="${y+20}" x2="335" y2="${y-20}" class="contact"/>

<text x="285" y="${y+40}" class="label">
Stop_PB
</text>

<!-- Coil -->
<path d="
M 500 ${y-20}
Q 470 ${y} 500 ${y+20}

M 540 ${y-20}
Q 570 ${y} 540 ${y+20}
" class="coil"/>

<text x="485" y="${y+40}" class="label">
Motor_M1
</text>

`;

}

async function downloadPDF(){

const { jsPDF } = window.jspdf;

const pdf = new jsPDF();

pdf.setFontSize(18);

pdf.text(
"PLC Ladder Logic Report",
20,
20
);

pdf.setFontSize(12);

pdf.text(
"Generated by PLC Ladder Logic Generator",
20,
40
);

pdf.text(
"Rung 1: Start/Stop Motor Circuit",
20,
60
);

pdf.save("PLC_Ladder_Logic.pdf");

}
