function generateLogic(){

  const plc =
  document.getElementById("plcModel").value;

  const logic =
  document.getElementById("logicType").value;

  const prompt =
  document.getElementById("prompt").value;

  const svg =
  document.getElementById("ladderSVG");

  svg.innerHTML = `
  
  <!-- Left Rail -->
  <line x1="50" y1="20" x2="50" y2="450" class="rail"/>

  <!-- Right Rail -->
  <line x1="950" y1="20" x2="950" y2="450" class="rail"/>
  
  `;

  drawMotorRung(100);

  generateTagTable(plc, logic, prompt);

}

function drawMotorRung(y){

  const svg =
  document.getElementById("ladderSVG");

  svg.innerHTML += `

  <!-- Rung -->
  <line x1="50" y1="${y}" x2="950" y2="${y}" class="rung"/>

  <!-- XIC -->
  <line x1="150" y1="${y-20}" x2="150" y2="${y+20}" class="contact"/>
  <line x1="180" y1="${y-20}" x2="180" y2="${y+20}" class="contact"/>

  <text x="130" y="${y+40}" class="label">
  Start_PB
  </text>

  <!-- XIO -->
  <line x1="300" y1="${y-20}" x2="300" y2="${y+20}" class="contact"/>
  <line x1="330" y1="${y-20}" x2="330" y2="${y+20}" class="contact"/>

  <line x1="295" y1="${y+20}" x2="335" y2="${y-20}" class="contact"/>

  <text x="285" y="${y+40}" class="label">
  Stop_PB
  </text>

  <!-- TON -->
  <rect x="420" y="${y-25}" width="100" height="50"
  stroke="black" fill="white" stroke-width="3"/>

  <text x="450" y="${y+5}" class="label">
  TON T4:0
  </text>

  <!-- OTE Coil -->
  <path d="
  M 700 ${y-20}
  Q 670 ${y} 700 ${y+20}

  M 740 ${y-20}
  Q 770 ${y} 740 ${y+20}
  " class="coil"/>

  <text x="680" y="${y+40}" class="label">
  Motor_M1
  </text>

  `;
}

function generateTagTable(plc, logic, prompt){

  let tags = `

  <table>

    <tr>
      <th>PLC Model</th>
      <th>Logic Type</th>
      <th>User Requirement</th>
    </tr>

    <tr>
      <td>${plc}</td>
      <td>${logic}</td>
      <td>${prompt}</td>
    </tr>

  </table>

  <table>

    <tr>
      <th>Address</th>
      <th>Tag</th>
      <th>Description</th>
    </tr>

    <tr>
      <td>I:0/0</td>
      <td>Start_PB</td>
      <td>Start Push Button</td>
    </tr>

    <tr>
      <td>I:0/1</td>
      <td>Stop_PB</td>
      <td>Stop Push Button</td>
    </tr>

    <tr>
      <td>T4:0</td>
      <td>Motor_Timer</td>
      <td>Motor Delay Timer</td>
    </tr>

    <tr>
      <td>O:0/0</td>
      <td>Motor_M1</td>
      <td>Motor Starter Output</td>
    </tr>

  </table>

  `;

  document.getElementById("tagTable").innerHTML =
  tags;

}

async function downloadPDF(){

  const { jsPDF } = window.jspdf;

  const pdf = new jsPDF();

  pdf.setFontSize(20);

  pdf.text(
    "PLC Ladder Logic Report",
    20,
    20
  );

  pdf.setFontSize(12);

  const plc =
  document.getElementById("plcModel").value;

  const logic =
  document.getElementById("logicType").value;

  const prompt =
  document.getElementById("prompt").value;

  pdf.text(`PLC Model: ${plc}`,20,40);

  pdf.text(`Logic Type: ${logic}`,20,50);

  pdf.text(`Requirement: ${prompt}`,20,60);

  pdf.text("Generated Tags:",20,80);

  pdf.text("I:0/0  - Start Push Button",20,95);
  pdf.text("I:0/1  - Stop Push Button",20,105);
  pdf.text("T4:0   - Motor Timer",20,115);
  pdf.text("O:0/0  - Motor Output",20,125);

  pdf.text(
    "Generated by PLC Ladder Logic Generator",
    20,
    150
  );

  pdf.save("PLC_Ladder_Logic_Report.pdf");

}
