function generateLogic(){

  const plc =
  document.getElementById("plcModel").value;

  const logic =
  document.getElementById("logicType").value;

  const prompt =
  document.getElementById("prompt").value;

  const svg =
  document.getElementById("ladderSVG");

  // Reset SVG
  svg.innerHTML = `

    <!-- Left Rail -->
    <line
      x1="50"
      y1="20"
      x2="50"
      y2="450"
      class="rail" />

    <!-- Right Rail -->
    <line
      x1="1000"
      y1="20"
      x2="1000"
      y2="450"
      class="rail" />

  `;

  // Draw Rung
  drawMotorRung(120);

  // Generate Tag Table
  generateTagTable(plc, logic, prompt);

}

function drawMotorRung(y){

  const svg =
  document.getElementById("ladderSVG");

  svg.innerHTML += `

    <!-- Rung -->
    <line
      x1="50"
      y1="${y}"
      x2="1000"
      y2="${y}"
      class="rung" />

    <!-- XIC Start -->
    <line
      x1="160"
      y1="${y-20}"
      x2="160"
      y2="${y+20}"
      class="contact" />

    <line
      x1="190"
      y1="${y-20}"
      x2="190"
      y2="${y+20}"
      class="contact" />

    <text
      x="130"
      y="${y+45}"
      class="label">

      Start_PB

    </text>

    <!-- XIO Stop -->
    <line
      x1="320"
      y1="${y-20}"
      x2="320"
      y2="${y+20}"
      class="contact" />

    <line
      x1="350"
      y1="${y-20}"
      x2="350"
      y2="${y+20}"
      class="contact" />

    <line
      x1="315"
      y1="${y+20}"
      x2="355"
      y2="${y-20}"
      class="contact" />

    <text
      x="295"
      y="${y+45}"
      class="label">

      Stop_PB

    </text>

    <!-- Timer -->
    <rect
      x="450"
      y="${y-25}"
      width="110"
      height="50"
      class="timer-box" />

    <text
      x="475"
      y="${y+5}"
      class="label">

      TON T4:0

    </text>

    <!-- Coil -->
    <path
      d="
      M 760 ${y-20}
      Q 730 ${y} 760 ${y+20}

      M 800 ${y-20}
      Q 830 ${y} 800 ${y+20}
      "
      class="coil" />

    <text
      x="720"
      y="${y+45}"
      class="label">

      Motor_M1

    </text>

  `;

}

function generateTagTable(plc, logic, prompt){

  let table = `

    <table>

      <tr>
        <th>PLC Model</th>
        <th>Logic Type</th>
        <th>User Requirement</th>
      </tr>

      <tr>
        <td>${plc}</td>
        <td>${logic}</td>
        <td>${prompt}</td>
      </tr>

    </table>

    <table>

      <tr>
        <th>Address</th>
        <th>Tag</th>
        <th>Description</th>
      </tr>

      <tr>
        <td>I:0/0</td>
        <td>Start_PB</td>
        <td>Start Push Button</td>
      </tr>

      <tr>
        <td>I:0/1</td>
        <td>Stop_PB</td>
        <td>Stop Push Button</td>
      </tr>

      <tr>
        <td>T4:0</td>
        <td>Motor_Timer</td>
        <td>Motor Delay Timer</td>
      </tr>

      <tr>
        <td>O:0/0</td>
        <td>Motor_M1</td>
        <td>Motor Starter Output</td>
      </tr>

    </table>

  `;

  document.getElementById("tagTable").innerHTML =
  table;

}

async function downloadPDF(){

  const { jsPDF } = window.jspdf;

  const pdf = new jsPDF();

  const plc =
  document.getElementById("plcModel").value;

  const logic =
  document.getElementById("logicType").value;

  const prompt =
  document.getElementById("prompt").value;

  pdf.setFontSize(22);

  pdf.text(
    "AI Master Vijay",
    20,
    20
  );

  pdf.setFontSize(18);

  pdf.text(
    "PLC Ladder Logic Report",
    20,
    35
  );

  pdf.setFontSize(12);

  pdf.text(
    `PLC Model: ${plc}`,
    20,
    55
  );

  pdf.text(
    `Logic Type: ${logic}`,
    20,
    65
  );

  pdf.text(
    `Requirement: ${prompt}`,
    20,
    75
  );

  pdf.text(
    "Generated Tags:",
    20,
    95
  );

  pdf.text(
    "I:0/0  - Start Push Button",
    20,
    110
  );

  pdf.text(
    "I:0/1  - Stop Push Button",
    20,
    120
  );

  pdf.text(
    "T4:0   - Motor Timer",
    20,
    130
  );

  pdf.text(
    "O:0/0  - Motor Output",
    20,
    140
  );

  pdf.text(
    "Generated by AI Master Vijay",
    20,
    170
  );

  pdf.save(
    "PLC_Ladder_Logic_Report.pdf"
  );

}
